# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPM-Make-Simple
version:      0.01
version_from: Simple.pm
installdirs:  site
requires:
    RPM::Make:                     0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
